import { colors, typography, radius, shadows, spacing } from "../design-system";

export const T = {
  // Compatibility layer for existing app styles.
  primary: colors.brand.primary,
  primaryActive: colors.brand.primaryHover,
  primaryDisabled: colors.bg.subtle,
  ink: colors.text.strong,
  body: colors.text.body,
  muted: colors.text.muted,
  mutedSoft: colors.text.disabled,
  hairline: colors.border.subtle,
  hairlineSoft: colors.border.soft,
  borderStrong: colors.border.strong,
  canvas: colors.bg.surface,
  canvasOuter: colors.bg.canvas,
  surfaceSoft: colors.bg.soft,
  surfaceStrong: colors.bg.subtle,
  onPrimary: colors.text.inverse,
  error: colors.state.danger,
  gold: "#c98a3e",
  goldSoft: "#f2dfc0",
  sage: "#5c6b4f",
  shadow: shadows.md,
  font: typography.family,
  spacing,
  type: typography,
  radius,
  rSm: radius.sm,
  rMd: radius.md,
  rLg: radius.lg,
  rXl: radius.xl,
  rFull: radius.pill,
};
